### ISSUE TITLE
install error - rpmbuild needed

### ISSUE THREAD

**Issue by zeustrismegistus** [Rudd-O/qubes-pass#1]
I'm getting an install error on a virgin vm (Qubes 3.2).  It's missing the rpmbuild dependency.  rpmbuild isn't in the default fedora image.   The line "sudo dnf install rpm-build" should be added to the build steps.

Below are the steps to replicate.  

git clone https://github.com/Rudd-O/qubes-pass
cd qubes-pass
make rpm

This outputs the following:
find -name '*~' -print0 | xargs -0 rm -fv
rm -fv *.tar.gz *.rpm
excludefrom= ; test -f .gitignore && excludefrom=--excludefrom=.gitignore ; DIR=qubes-pass-`awk '/^Version:/ {print $2}' qubes-pass.spec` && FILENAME=$DIR.tar.gz && tar cvzf "$FILENAME" --exclude="$FILENAME" --exclude=.git --exclude=.gitignore $excludefrom --transform="s|^|$DIR/|" --show-transformed *
qubes-pass-0.0.6/bin/
qubes-pass-0.0.6/bin/qvm-pass
qubes-pass-0.0.6/bin/qubes-pass-client
qubes-pass-0.0.6/etc/
qubes-pass-0.0.6/etc/qubes-rpc/
qubes-pass-0.0.6/etc/qubes-rpc/ruddo.PassRead
qubes-pass-0.0.6/etc/qubes-rpc/policy/
qubes-pass-0.0.6/etc/qubes-rpc/policy/ruddo.PassRead
qubes-pass-0.0.6/etc/qubes-rpc/policy/ruddo.PassManage
qubes-pass-0.0.6/etc/qubes-rpc/ruddo.PassManage
qubes-pass-0.0.6/Makefile
qubes-pass-0.0.6/qubes-pass.spec
qubes-pass-0.0.6/README.md
T=`mktemp -d` && rpmbuild --define "_topdir $T" -ta qubes-pass-`awk '/^Version:/ {print $2}' qubes-pass.spec`.tar.gz || { rm -rf "$T"; exit 1; } && mv "$T"/RPMS/*/* "$T"/SRPMS/* . || { rm -rf "$T"; exit 1; } && rm -rf "$T"
/bin/sh: rpmbuild: command not found
Makefile:14: recipe for target 'rpm' failed
make: *** [rpm] Error 1

**Comment by Rudd-O** [comment]
Fixed!
