### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by corvus-ch** [Rudd-O/qubes-pass#10]
Extensions to pass like [pass-otp](https://github.com/tadfisher/pass-otp) are made available as a new sub command. When trying to use them through qubes-pass, they do not get executed. Instead, a password is searched for that subcommand name (for example `otp`).

Would it be possible to add support for such extensions to qubes-pass?

**Comment by Rudd-O** [comment]
Uh, that would not be possible with the current architecture of this program.  Sorry.

What really needs to happen is a rewrite of `pass` itself, where the backend is abstracted away from the frontend, so that `pass` can use a Qubes backend or a local files backend.
