### ISSUE TITLE
qrcode and clip features are undocumented and possibly broken

### ISSUE THREAD

**Issue by mtdcr** [Rudd-O/qubes-pass#13]
I tried to use both `--qrcode` and `--clip`, but somehow these options didn't have any effect. Can you please provide a working example command-line?

Last year, I took a different approach at implementing the clip option. Feel free to take this as inspiration, if you want, but it's incomplete: https://github.com/mtdcr/qubes-pass/commit/f82bd1a58ec05add06e140eb9ca6abe30b62ddec

**Comment by Rudd-O** [comment]
Huh, you're right.

**Comment by Rudd-O** [comment]
0.0.30 fixes it.  Now released.
