### ISSUE TITLE
Options clip and qrcode leak secrets into the process list

### ISSUE THREAD

**Issue by mtdcr** [Rudd-O/qubes-pass#14]
By passing everything to bash -c, qvm-pass leaks secrets on the command-line.

To reproduce:
```sh
qvm-pass get-or-generate test
qvm-pass -c test
ps -ef | grep clip
```
Maybe unrelated, but maybe caused by recent changes: `echo foo | qvm-pass insert -e test` didn't work for me. `qvm-pass -c get-or-generate` didn't work either, but I think that was intended.

**Comment by Rudd-O** [comment]
OK!  I've fixed the `qvm-pass insert -e` issue, and I cannot repro `qvm-pass -c get-or-generate` not working (it works fine here).

Sadly, you should note that the code we are using to `xclip` or `qrcode` comes **straight from pass**, so `pass` does the exact same thing (minus the `bash -c`, but that doesn't matter as the passwords are in fact (even if briefly) put in the process list of your system, whether you use `qvm-pass` or `pass` alone.

**Comment by Rudd-O** [comment]
```
clip() {
	if [[ -n $WAYLAND_DISPLAY ]]; then
		local copy_cmd=( wl-copy )
		local paste_cmd=( wl-paste -n )
		if [[ $X_SELECTION == primary ]]; then
			copy_cmd+=( --primary )
			paste_cmd+=( --primary )
		fi
		local display_name="$WAYLAND_DISPLAY"
	elif [[ -n $DISPLAY ]]; then
		local copy_cmd=( xclip -selection "$X_SELECTION" )
		local paste_cmd=( xclip -o -selection "$X_SELECTION" )
		local display_name="$DISPLAY"
	else
		die "Error: No X11 or Wayland display detected"
	fi
	local sleep_argv0="password store sleep on display $display_name"

	# This base64 business is because bash cannot store binary data in a shell
	# variable. Specifically, it cannot store nulls nor (non-trivally) store
	# trailing new lines.
	pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5
	local before="$("${paste_cmd[@]}" 2>/dev/null | $BASE64)"
	echo -n "$1" | "${copy_cmd[@]}" || die "Error: Could not copy data to the clipboard"
	(
		( exec -a "$sleep_argv0" bash <<<"trap 'kill %1' TERM; sleep '$CLIP_TIME' & wait" )
		local now="$("${paste_cmd[@]}" | $BASE64)"
		[[ $now != $(echo -n "$1" | $BASE64) ]] && before="$now"

		# It might be nice to programatically check to see if klipper exists,
		# as well as checking for other common clipboard managers. But for now,
		# this works fine -- if qdbus isn't there or if klipper isn't running,
		# this essentially becomes a no-op.
		#
		# Clipboard managers frequently write their history out in plaintext,
		# so we axe it here:
		qdbus org.kde.klipper /klipper org.kde.klipper.klipper.clearClipboardHistory &>/dev/null

		echo "$before" | $BASE64 -d | "${copy_cmd[@]}"
	) >/dev/null 2>&1 & disown
	echo "Copied $2 to clipboard. Will clear in $CLIP_TIME seconds."
}
```

See this code?  It `echo`es the password into the process list.  That's from `pass`.

I will see if I can make improvements to it — onno, perhaps passing the password via a FIFO or something — but I highly doubt that.

**Comment by Rudd-O** [comment]
I have released a new version of qubes-pass just now, which addresses the concern by using a private FIFO pipe instead of passing any arguments on the command line.

**Comment by Rudd-O** [comment]
A new version was released just now, which instead of using FIFOs (which can be fragile) it simply base64 encodes the code that bash is supposed to run for us (that's the pesky `pass` code), and then decodes it on bash's side — we send it via **stdin** instead, which is private although ideally it should be mlocked.

**Comment by mtdcr** [comment]
> Sadly, you should note that the code we are using to xclip or qrcode comes straight from pass, so pass does the exact same thing (minus the bash -c, but that doesn't matter as the passwords are in fact (even if briefly) put in the process list of your system, whether you use qvm-pass or pass alone.

`echo` is a shell builtin (see `bash-builtins(7)`, for example), so it won't spawn a new process.

Passing the data via stdin is probably fine, but I think invoking bash for `-c` and `-q` was a bad design decision, in general.
