### ISSUE TITLE
.deb package - read - "illegal option -n"

### ISSUE THREAD

**Issue by 19hundreds** [Rudd-O/qubes-pass#2]
This is not an issue but a note for those who, like me, are testing this brilliant piece of software **and** lazily built their .deb (for debian based AppVm) using alien starting from the .rpm packages

When you run `qvm-pass init` in the password manager vm you should see this error:

```/etc/qubes-rpc/ruddo.PassManage: 5: read: Illegal option -n```

This is, most likely, due to the alien conversion from "rpm" to "deb" but I'm not sure at this stage. 

However, to fix it: open a terminal in the _password store virtual machine_ and

```chmod 755 /etc/qubes-rpc/ruddo.Pass*```

Run `qvm-pass init` again

**Comment by tracihaire** [comment]
Q.

**Comment by tracihaire** [comment]
Cool

**Comment by Istador** [comment]
Thanks for providing a workaround.

Your conversion to `deb` seems to be correct regarding to the permissions.

It should be changed in the `Makefile` from 644 to 755:
https://github.com/Rudd-O/qubes-pass/blob/2eea0c93457fd4d02e7a57f6c39e605d771b0c09/Makefile#L28-L29

**Comment by Rudd-O** [comment]
Fixed!  Thank you!
