### ISSUE TITLE
Support 'show' as alias to 'list'/'get' - passff browser extension compatibility

### ISSUE THREAD

**Issue by fabiogermann** [Rudd-O/qubes-pass#3]
The default command to show passwords for passff is 'show', however this command is not available in qvm-pass. Therefore it does not work out of the box with the passff browser extension.

The debug output to identify if it is working with the extension: 
`echo -e "\x02\x00\x00\x00[]" | /path/to/passff.py | tail -c +4; echo` documented in passff-host [source](https://github.com/passff/passff-host)
where the output should be:
`{"stderr": "", "version": "1.0.1", "exitCode": 0, "stdout": "Password Store\n"}`

With qvm-pass it is currently: 
`{"stderr": "Error: show is not in the password store.\n", "version": "1.0.1", "exitCode": 8, "stdout": ""}`

My temporary workaround is to change the command in `passff.py` lines 63 from `show` to `list` and 83 from `show` to `get`.

Ideally qvm-pass would allow `show` without further argument to alias to `list` and `show` with additional argument to `get`.

**Comment by Rudd-O** [comment]
Is this fixed?  Please close if the latest push and version fixes the issue.  Thank you!

**Comment by Rudd-O** [comment]
Sorry, mistakenly closed.  Please keep open if the bug persists in `master` or latest tag, and make a note here.  If it's closed, it's yours to close.  Thank you.

**Comment by Rudd-O** [comment]
I am closing this due to f3591faf957503d3911b3d06b737321c55cf2a8c that should have implemented the feature request, and no response in a year.
