### ISSUE TITLE
No '-c' argument to `qvm-pass generate`.  Lots of weird (ANSI?) terminal sequences in result.

### ISSUE THREAD

**Issue by BetoHydroxyButyrate** [Rudd-O/qubes-pass#6]
First of all, thanks for this.  I have learned more about Qubes in trying to understand this than I have for the past `n` years as an intermittent user.

`$ qvm-pass -c generate -n test/t0 128` results in: `qvm-pass: error: unrecognized arguments: -c`

If I remove the `-c` then I am presented with:
```
$ qvm-pass generate -n test/t0 128
mkdir: created directory '/home/user/.password-store/test'
_[1mThe generated password for _[4mtest/t0_[24m is:_[0m
_[1m_[93ma7gzXcYi2OrTDOeQB3n5WQagjT85GfqGQAJdPjNQ43hBEifN2lDHQAvak0bucRttKIzCn8mFUNAKM8xG0Go1VfHR2dYgFfC3sflyzmhQKT4XwrMDajLKHMwj79EQ2pjH_[0m
```
For me, this is not usable.

I note that the `qvm-pass ls` output is not optimised for my `$TERM` setting.
This is how the output appears from the AppVM where `pass` runs:

```
Password Store
└── test
    ├── t0
    ├── t1
    └── t3
```
Here is how it is presented on the client-side.  Note the above is coloured, below is not.
```
$ qvm-pass ls
Password Store
_________ test
    _________ t0
    _________ t1
    _________ t3

```

**Comment by BetoHydroxyButyrate** [comment]
Turns out if I add: `export TERM=xterm-256color` to both  the `ruddo` shell scripts, I get the correct ANSI sequences for my terminal.
However, there is some weird stuff happening in the python subprocess output.  Is it paginated?

```
$ qvm-pass ls 
Password Store
_________ _[01;34mtest_[0m
    _________ t0
$ qvm-pass ls | cat
Password Store
└── test
    └── t0
```

**Comment by BetoHydroxyButyrate** [comment]
Added some flags to the call to `qrexec-client-vm` to insist on not stripping the control chars.
```
def send_args(rpc, *args, **kwargs):
    cmd = ['/usr/lib/qubes/qrexec-client-vm',
            '--no-filter-escape-chars-stdout',
            '--no-filter-escape-chars-stderr',
            opts.dest_vm, rpc]
```

```
$ qvm-pass generate -n test/t001 128 
The generated password for test/t001 is:
UotdJ4PgTpehTKNP4MlNqD91FqAZx0ghqqhk9uErgRI8009JUMhhtStK3cBQW3aMHCbaJegYgxVgNCY8WGLWz03Kmm35oFoF6nob3VB3aX4W3stsHB0bchfOMxdSKNg4
```

I guess I'll try to figure out how to make these changes to a fork and the generate a pull?

Still want the `-c` arg and also `edit` option which I use a lot.  Well, more than never.

**Comment by Rudd-O** [comment]
Did the merged PR and new release fix your issue?

**Comment by Rudd-O** [comment]
I would welcome a PR that enables the `-c` option!

**Comment by Rudd-O** [comment]
The `-c` and `-q` functionality has been ported from `pass` to `qvm-pass`.

**Comment by Rudd-O** [comment]
(Check tag v0.0.24)
